[tool.poetry]
name = "projecttemplate"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-randomly = "*"

mypy = "*"
coverage = "*"

# check hook versions in .pre-commit-config.yaml and update if outdated
pre-commit = "*"

[tool.black]
line-length = 79
target-version = ['py38']

[tool.isort]
known_third_party = []

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
